### ISSUE TITLE
增加类目排序分类功能

### ISSUE THREAD

**Issue by zwei8908** [hoperyy/vue-markdown-book#1]
RT

**Comment by hoperyy** [comment]
@zwei8908  done: 

Code: https://github.com/hoperyy/vue-markdown-book/commit/55b29ebec25570f544c6de0928511ba303bd5976

Readme: https://github.com/hoperyy/vue-markdown-book

![image](https://user-images.githubusercontent.com/5757051/29751632-994edf46-8b82-11e7-8c9a-bcea78ea5baf.png)
